name: coverals

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test
      run: |
        echo "VITE_APP_ENCRYPT_STORAGE_SECRET_KEY=eec61fa0-77bc-4cde-a3f9-052314bcdb8d >> .env"
        echo "VITE_APP_ENCRYPT_STORAGE_PREFIX=@ubook >> .env"
        echo "VITE_APP_NODE_ENV=production >> .env"
        yarn install
        yarn test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
        VITE_APP_ENCRYPT_STORAGE_SECRET_KEY: "eec61fa0-77bc-4cde-a3f9-052314bcdb8d"
        VITE_APP_ENCRYPT_STORAGE_PREFIX: "@ubook"
        VITE_APP_NODE_ENV: "production"
      with:
        github-token: ${{ github.token }}
